project_name: starter-go-cobra

builds:
  - env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm
      - arm64

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

brews:
  - tap:
      owner: pthomison
      name: homebrew-tools

nfpms:
  - 
    formats:
      - apk
      - deb
      - rpm
      
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

before:
  hooks:
    - go mod tidy
    - go fmt ./...

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64